# Generated by Django 5.0.1 on 2024-01-25 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_hidden', models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрыт из показа')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название блюда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('measure', models.CharField(choices=[('гр.', 'Gram'), ('кг.', 'Kilogram'), ('мл.', 'Milliliter'), ('л.', 'Liter')], default='гр.', max_length=3, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
                ('promotional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена с введенным  промокодом')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка в процентах')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время заказа')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма заказа')),
                ('payment_method', models.CharField(choices=[('Оплата курьеру', 'Cash'), ('Оплата онлайн', 'Online')], default='Оплата онлайн', max_length=14, verbose_name='Способ оплаты')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='Товары в заказе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
