# Generated by Django 5.0.2 on 2024-03-10 22:00

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID категории из iikoWeb')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_hidden', models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрыт из показа')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя получателя рассылки о заказх')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID телеграма')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость покупок в корзине')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя покупателя')),
                ('buyer_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время заказа')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма заказа')),
                ('payment_method', models.CharField(choices=[('to_courier', 'Cash'), ('online', 'Online')], default='to_courier', max_length=14, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('courier', 'Courier'), ('pickup', 'Pickup')], default='courier', max_length=7, verbose_name='Способ доставки')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID категории из iikoWeb')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название блюда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('measure', models.CharField(choices=[('гр.', 'Gram'), ('кг.', 'Kilogram'), ('мл.', 'Milliliter'), ('л.', 'Liter')], default='гр.', max_length=3, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Текущая цена')),
                ('temporary_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Временная цена')),
                ('is_hidden', models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрыт из показа')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Текущая цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='main.CartItem', to='main.product'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название промо')),
                ('discount_percentage', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('max_usage_count', models.SmallIntegerField(default=1, verbose_name='Максимально кол-во использований для одного клиента')),
                ('current_usage_count', models.SmallIntegerField(default=0, verbose_name='Текущее кол-во использований')),
                ('promo_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Товар в подарок')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promo', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promo', verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promo', verbose_name='Промо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_product_1', to='main.product', verbose_name='РРекомендованный товар 1')),
                ('product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_product_2', to='main.product', verbose_name='Рекомендованный товар 2')),
                ('product_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_product_3', to='main.product', verbose_name='Рекомендованный товар 3')),
            ],
            options={
                'verbose_name': 'Рекомендованный товар',
                'verbose_name_plural': 'Рекомендованные товары',
            },
        ),
    ]
