# Generated by Django 5.0.2 on 2024-03-18 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_start', models.TimeField(blank=True, null=True, verbose_name='Время начала акции')),
                ('time_to_end', models.TimeField(blank=True, null=True, verbose_name='Время конца акции')),
                ('discount_percentage', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Счастливые часы',
                'verbose_name_plural': 'Акция Счастливые часы',
            },
        ),
    ]
