# Generated by Django 5.0.2 on 2024-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_happyhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_happy_hours',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Акция Счастливые часы'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_happy_hours',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Акция Счастливые часы'),
        ),
    ]
