FROM nginx:1.25
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
#RUN mkdir /etc/nginx/certs
#COPY .server.crt /etc/nginx/certs/server.crt
#COPY .server.key /etc/nginx/certs/server.key
