# Generated by Django 5.0.2 on 2024-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Внешнее меню',
                'verbose_name_plural': 'Внешние меню',
            },
        ),
        migrations.CreateModel(
            name='IikoAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(verbose_name='API Ключ компании')),
            ],
            options={
                'verbose_name': 'Ключ компании',
                'verbose_name_plural': 'Ключи компании из iikoWeb',
            },
        ),
    ]
