# Generated by Django 5.0.2 on 2024-03-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ценовая категория iikoWeb',
                'verbose_name_plural': 'Ценовые категории iikoWeb',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организация из iikoWeb',
                'verbose_name_plural': 'Организации из iikoWeb',
            },
        ),
        migrations.AlterModelOptions(
            name='externalmenu',
            options={'verbose_name': 'Внешнее меню iikoWeb', 'verbose_name_plural': 'Внешние меню iikoWeb'},
        ),
        migrations.RemoveField(
            model_name='externalmenu',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalmenu',
            name='menu_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
