# Generated by Django 5.0.2 on 2024-03-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_category_organization_alter_externalmenu_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
