# Generated by Django 5.0.4 on 2024-04-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.externalmenu', verbose_name='ID Меню')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.organization', verbose_name='ID организации')),
            ],
            options={
                'verbose_name': 'Сохранить меню',
            },
        ),
    ]
