# Generated by Django 5.0.4 on 2024-04-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_fetchmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fetchmenu',
            options={'verbose_name': 'Сохранить меню', 'verbose_name_plural': 'Сохранить меню'},
        ),
    ]
